name: Deploy Servlet App

on:
  push:
    branches: [dev]
  pull_request:
    branches: [dev]
jobs:
   deploy:
    runs-on: self-hosted

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Setup JDKd
      uses: actions/setup-java@v2
      with:
           java-version: '11'
           distribution: 'adopt'
           java-package: 'jdk'
           architecture: 'x64'
           check-latest: false
           server-id: 'github'
           server-username: ${{ github.actor }}
           server-password: ${{ secrets.GITHUB_TOKEN }}
           overwrite-settings: true
           job-status: 'success'

    - name: Build with Maven
      run: mvn clean package
      

    - name: Copy WAR file to IIS directory
      run: |
        cd target
        # Copy the WAR file to the directory where IIS is configured for Java Servlet applications
        dir
        ls 
        java -jar sample-0.0.1-SNAPSHOT.jar
         # Remove-Item -Path "C:\testdemo" -Recurse -Force 
            Get-ChildItem -Path "C:\testdemo" | Remove-Item -Recurse -Force
            Copy-Item -Path "dist/achieve-ui/browser/*" -Destination "C:/testdemo" -Recurse -Force
            Copy-Item -Path "dist/achieve-ui/3rdpartylicenses.txt" -Destination "C:/testdemo" -Force

        
        
    - name: Restart IIS
      run: |
        # Restart IIS to apply changes
